INSERT INTO `toggle_all` (`feature`, `percent`, `type`, `description`, `label`, `plan`)
VALUES
('admin', 100, 'advanced', '', '', ''),
('progressTask', 100, 'advanced', '', '', ''),
('deleteContact', 100, 'advanced', '', '', ''),
('advancedSearch', 100, 'advanced', '', '', ''),
('personalization', 100, 'advanced', '', '', ''),
('mailchimp', 100, 'advanced', '', '', ''),
('mergeContact', 100, 'advanced', '', '', ''),
('swapWithMoney', 100, 'advanced', '', '', ''),
('newCommunity', 100, 'advanced', '', '', ''),
('boomset', 100, 'advanced', '', '', ''),
('taxOnCheckout', 100, 'advanced', '', '', ''),
('newPollsUI', 100, 'advanced', '', '', ''),
('showRegistrationDashboard', 100, 'advanced', '', '', ''),
('googleTagManager', 100, 'advanced', '', '', ''),
('analyticsNew', 100, 'advanced', '', '', ''),
('ticketsTransfer', 100, 'advanced', '', '', ''),
('hotLeads', 100, 'advanced', '', '', ''),
('editPaymentCredentials', 100, 'advanced', '', '', ''),
('agendaSBSView', 100, 'advanced', '', '', ''),
('agendaAnalytics', 100, 'advanced', '', '', ''),
('agendaAnalyticsSpeakers', 100, 'advanced', '', '', ''),
('agendaBanner', 100, 'advanced', '', '', ''),
('useTokensCache', 100, 'advanced', '', '', ''),
('crossEventAnalyticsV2', 100, 'advanced', '', '', ''),
('agendaSessReg', 100, 'advanced', '', '', ''),
('enableAptrinsicTool', 100, 'advanced', '', '', ''),
('speakersManageOrders', 100, 'advanced', '', '', ''),
('lockerAgendaAnalytics', 100, 'advanced', '', '', ''),
('newCustomElement', 100, 'advanced', '', '', ''),
('eventProperties', 100, 'advanced', '', '', ''),
('ticketsDownloadReport', 100, 'advanced', '', '', ''),
('crossEventsEngagement', 100, 'advanced', '', '', ''),
('emailsCampaigns', 100, 'advanced', '', '', ''),
('eventPropertiesNewUrls', 100, 'advanced', '', '', ''),
('scheduledEmailCampaigns', 100, 'advanced', '', '', ''),
('zendeskHelpCenter', 100, 'advanced', '', '', ''),
('newRolesAttributeUrl', 100, 'advanced', '', '', ''),
('getSeparatedContactsList', 100, 'advanced', '', '', ''),
('reactSection', 100, 'advanced', '', '', ''),
('archiveEvent', 100, 'advanced', '', '', ''),
('stripe3ds', 100, 'advanced', '', '', ''),
('switchTheme', 100, 'advanced', '', '', ''),
('switchThemeLivePreview', 100, 'advanced', '', '', ''),
('newSectionLayout', 100, 'advanced', '', '', ''),
('enableInsightsDashboardDetails', 100, 'advanced', '', '', ''),
('accountLevelContactSearch', 100, 'advanced', '', '', ''),
('segmentPush', 100, 'advanced', '', '', ''),
('agendaShare', 100, 'advanced', '', '', ''),
('hideEventDates', 100, 'advanced', '', '', ''),
('inSidedSSO', 100, 'advanced', '', '', ''),
('hideSessionDates', 100, 'advanced', '', '', ''),
('sessionModerators', 100, 'advanced', '', '', ''),
('liveNowBanner', 100, 'advanced', '', '[Virtual] Agenda Live Now Banner', ''),
('sessionRegistration', 0, 'package', '', '[Agenda] Session Registraion', 'pro' ),
('showRevenueDashboard', 0, 'package', '', '[Dashboard] Show Revenue Dashabord', '' ),
('showEmailMarketingDashboard', 0, 'package', '', '[Email] Analytics Email', '' ),
('brandingPackage', 0, 'package', '', '[Branding] Branding Package', 'pro' ),
('websiteCss', 0, 'advanced', '', '[Website Editor] Custom CSS', '' ),
('customJs', 0, 'advanced', '', '[Website Editor] Custom JavaScript', '' ),
('hideAmericanExpressIcon', 0, 'advanced', '', '[Registration] Hide Amex icon', '' ),
('apiKeys', 0, 'package', '', '[Integrations] Open Public API', 'elite' ),
('removeBranding', 0, 'advanced', '', '[Branding] Remove Bizzabo Branding', '' ),
('rtl', 0, 'advanced', 'For websites in Hebrew, Arabic', '[Website Editor] Right to Left', '' ),
('salesforce', 0, 'package', 'If chosen as the 1 included integration by the client...', '[Integrations] Salesforce integration', '' ),
('seo', 0, 'advanced', '', '[Website Editor] SEO', '' ),
('whiteLabelApp', 0, 'package', '', '[App] White Label Mobile App', '' ),
('White Label App - Only Navigation', 0, 'package', '', '[App] WLA Stores Settings', '' ),
('rsvpForm', 0, 'development', '', '[Registration] RSVP via form not registration (test)', '' ),
('removeTicketWidgetLinkedin', 0, 'advanced', '', '[Registration] Remove Linkedin Integration', '' ),
('whiteLabelDomain', 0, 'package', '', '[Branding] White Label Domain', '' ),
('customCode', 0, 'advanced', '', '[Website Editor] Custom Code', '' ),
('xtag', 0, 'package', '', '[Integrations] Xtag Onsite Solutions', '' ),
('PromoCodeImportXls', 0, 'advanced', '', '[Registration] Promo Code Import Xls', '' ),
('ticketSelectionPopover', 0, 'advanced', '', '[Registration] Ticket Selection Popover', '' ),
('valuesMappingEnabled', 0, 'advanced', '', '[Registration] Values Mapping Enabled', '' ),
('hideBizzaboTerms', 0, 'advanced', '', '[Registration] Hide Bizzabo Terms And Conditions (Upon Legal Team Approval)', '' ),
('companyListProfiles', 0, 'package', '', '[Companies] Companies feature', 'elite' ),
('autoOpenSessions', 0, 'advanced', '', '[Agenda] Session Preview Text Auto-Expend', '' ),
('disableMoreTabs', 0, 'advanced', '', '[Website Editor] Disable More Tabs', '' ),
('emailBuilderCodeView', 0, 'advanced', 'email code view and table capabilities will be added to the Body Element of the email builder.', '[Email] Email Builder Code View', '' ),
('analyticsDashboard', 0, 'package', '', '[Dashboard] Cross Events Analytics', 'elite' ),
('insightsDashboard', 0, 'package', '', '[Dashboard] Insights Audience + Cross Events Analytics', 'elite' ),
('testFeature', 0, 'development', '', '[Website Editor] Test Feature', '' ),
('closeReactSection-header', 0, 'advanced', '', '[Website Editor] Advanced Styles for Header Element', '' ),
('closeReactSection-downloadApp', 0, 'advanced', '', '[Website Editor] Advanced Styles for Download App Element', '' ),
('meetingsFeature', 0, 'development', '', '[Meetings] Meetings', '' ),
('sessionAssociation', 0, 'development', '', '[Agenda] Session Association Private Flow', '' ),
('emailSmartLink', 0, 'advanced', '', '[Email] Save A Seat Smart Link', '' ),
('disableTicketsDefaultQuantity', 0, 'advanced', '', '[Registration] Disable Tickets Default Quantity', '' ),
('personalizationCustomAttributes', 0, 'advanced', 'all registration attributes will be added to the Registration Confirmation campaigns (Automated Emails) personalization tag list.', '[Email] Personalization Custom Attributes', '' ),
('conditionalLogic', 0, 'advanced', '', '[Registration-RSVP] Conditional Logic', '' ),
('loginSSO', 0, 'package', '', '[Account] Login SSO', '' ),
('privateFlow', 0, 'advanced', '', '[Agenda] Private Flow', '' ),
('dynamicCcEnabled', 0, 'advanced', 'the option toggle CC per registrant/contact will be added to all automated/scheduled campaigns audience tab.', '[Email] Dynamic CC', '' ),
('ShareAudienceDashboardAction', 0, 'package', '', '[Dashboard] Insights - Share Dashboard ', 'elite' ),
('registrationCap', 0, 'advanced', '', '[Registration] Cap Limit Tickets', '' ),
('registrationV2Settings', 0, 'development', '', '[Registration] V2 Settings', '' ),
('closeReactSection-attendees', 0, 'development', '', '[Website Editor] Close React Section Attendees', '' ),
('disableUiForTicketsFetch', 0, 'development', '', '[Registration] Disable Ui For Tickets Fetch', '' ),
('ercFeature', 0, 'package', '', '[ERC] Partners Portal', '' ),
('srcFeature', 0, 'package', '', '[SRC] Speakers Portal', '' ),
('WLAPreviewImages', 0, 'package', '', '[App] WLA Stores Images Automation', '' ),
('closeReactSection-people', 0, 'development', '', '[Website Editor] Close React Section People', '' ),
('websiteTemplates', 0, 'advanced', '', '[Website Editor] Templates', '' ),
('ROEDashboard', 0, 'development', '', '[Dashboard] ROE Dashboard ', '' ),
('IHSCustomCountryLabel', 0, 'advanced', '', '[Registration] IHS Custom Country Label', '' ),
('scheduledCampaignResend', 0, 'advanced', '', '[Email] Scheduled Campaign Resend', '' ),
('resiadaIntegration', 0, 'advanced', '', '[Integrations] Resiada Hotel Platform', '' ),
('cloudinaryInlineContainer', 0, 'development', '', '[Unknown] Cloudinary Inline Container', '' ),
('Platform', 0, 'development', '', '[Unknown] Platform', '' ),
('dateTimePickerField', 0, 'advanced', '', '[Registration] Date Time Picker Field', '' ),
('sessionCasting', 0, 'package', '', '[Virtual] Bizzabo Interact (Interact + External solutions + Embedded player solution)', 'pro' ),
('srcInvoiceFeature', 0, 'development', '', '[SRC] Download Invoice Feature', '' ),
('importLinkedinProfileNewReg', 0, 'advanced', 'show linkedin import on RSVP. Should be turned on for those that want to use this feature. Will be replaced with a configuration on the dashboard in the future.', '[Registration] RSVP Linkedin Integration ', '' ),
('sessionCheckIn', 0, 'advanced', '', '[Agenda] Session Check In Data', '' ),
('enterpriseBuild', 0, 'development', 'To be enabled by WLA Project Manager', '[App] White Label App Enterprise Build', '' ),
('sessionCastingMegaSession', 0, 'package', '', '[Virtual] Bizzabo Stream', 'pro' ),
('unsubscribeToggle', 0, 'development', 'You need Bizzabo legal team approval to enable this FT', '[Email] Remove Unsubscribe Footer (Upon Legal Team Approval)', '' ),
('sessionRecording', 0, 'package', 'Enables recording of the virtual session', '[Virtual] Recording On-Demand', 'pro' ),
('AgendaVirtualAnalytics', 0, 'package', '', '[Virtual] Agenda Virtual Analytics', 'pro' ),
('sessionPrerecordedVideo', 0, 'development', '', '[Virtual] Pre Recorded Video - Simulive', ''),
('pollById', 0, 'advanced', '', '', '' ),
('Gotham', 0, 'font', '', '', ''),
('Geomanist', 0, 'font', '', '', ''),
('Plantagenet-Cherokee', 0, 'font', '', '', ''),
('Segoe-Ui', 0, 'font', '', '', ''),
('SuisseMono', 0, 'font', '', '', ''),
('MaquettePro', 0, 'font', '', '', ''),
('Flood', 0, 'font', '', '', ''),
('IvarText', 0, 'font', '', '', ''),
('Campton', 0, 'font', '', '', ''),
('Relative', 0, 'font', '', '', ''),
('Edo', 0, 'font', '', '', ''),
('Taz', 0, 'font', '', '', ''),
('AvenirNext', 0, 'font', '', '', ''),
('Cinetype', 0, 'font', '', '', ''),
('kievietFont', 0, 'font', '', '', ''),
('Calibri', 0, 'font', '', '', ''),
('Graphik', 0, 'font', '', '', ''),
('TitlingGothicCompressed', 0, 'font', '', '', ''),
('AdelleSans', 0, 'font', '', '', ''),
('Proxima', 0, 'font', '', '', ''),
('LeagueGothic', 0, 'font', '', '', ''),
('SEGFoco', 0, 'font', '', '', ''),
('LinetoCircular', 0, 'font', '', '', ''),
('GT-Pressura-Mono', 0, 'font', '', '', ''),
('Tungsten', 0, 'font', '', '', ''),
('Neue-Hass-Grotesk', 0, 'font', '', '', ''),
('Gilroy', 0, 'font', '', '', ''),
('GoogleSans', 0, 'font', '', '', ''),
('PostazBold-Regular', 0, 'font', '', '', ''),
('BarleyScript', 0, 'font', '', '', ''),
('Neue-Haas-Grotesk-Display', 0, 'font', '', '', ''),
('Inter', 0, 'font', '', '', ''),
('SalesforceSans', 0, 'font', '', '', ''),
('One-GT-Super-Display', 0, 'font', '', '', ''),
('GintoNormal', 0, 'font', '', '', ''),
('One-GT-Super-Text', 0, 'font', '', '', ''),
('Colfax', 0, 'font', '', '', ''),
('Franklin-Gothic-Book', 0, 'font', '', '', ''),
('Franklin-Gothic-Demi', 0, 'font', '', '', ''),
('Helvetica', 0, 'font', '', '', ''),
('Locator', 0, 'font', '', '', ''),
('OctoberMoon', 0, 'font', '', '', ''),
('CircularStd', 0, 'font', '', '', ''),
('ProximaNova-CS', 0, 'font', '', '', ''),
('MyriadPro', 0, 'font', '', '', ''),
('MyriadPro-Semi-Condensed', 0, 'font', '', '', ''),
('MyriadPro-Semi-Extended', 0, 'font', '', '', ''),
('LuxuryText', 0, 'font', '', '', ''),
('ArtegraSans', 0, 'font', '', '', ''),
('ZingRustBase', 0, 'font', '', '', ''),
('ZingRustHalftone', 0, 'font', '', '', ''),
('ZingRustLine', 0, 'font', '', '', ''),
('Franklin-Gothic-CnSC-Book', 0, 'font', '', '', ''),
('Franklin-Gothic-CnSC-Medium', 0, 'font', '', '', ''),
('Franklin-Gothic-CnSC-Medium', 0, 'font', '', '', ''),
('FranklinGothic-Ext-Comp-Boo', 0, 'font', '', '', ''),
('FranklinGothic-Cond-Book', 0, 'font', '', '', ''),
('FranklinGothic-Cond-Demi', 0, 'font', '', '', ''),
('Roska', 0, 'font', '', '', ''),
('BrandonGrotesque', 0, 'font', '', '', ''),
('AlternateGothic', 0, 'font', '', '', ''),
('DINPro', 0, 'font', '', '', ''),
('DirtyHeadline', 0, 'font', '', '', ''),
('Novecentowide', 0, 'font', '', '', ''),
('Futura-Condensed', 0, 'font', '', '', ''),
('Futura', 0, 'font', '', '', ''),
('Segoe-Ui-Light', 0, 'font', '', '', ''),
('Segoe-Ui-SemiBold', 0, 'font', '', '', ''),
('Segoe-Ui-SemiLight', 0, 'font', '', '', ''),
('Fabrikat-Mono', 0, 'font', '', '', ''),
('NexaSlab', 0, 'font', '', '', ''),
('UniNeue', 0, 'font', '', '', ''),
('Gotham-Condensed', 0, 'font', '', '', ''),
('Gotham-Rounded', 0, 'font', '', '', ''),
('BureauGrotesque-Five', 0, 'font', '', '', ''),
('BureauGrotesque-One', 0, 'font', '', '', ''),
('BureauGrotesque-Seven', 0, 'font', '', '', ''),
('BureauGrotesque-Three', 0, 'font', '', '', ''),
('CompassSans', 0, 'font', '', '', ''),
('CompassSerif', 0, 'font', '', '', ''),
('EuclidFlex', 0, 'font', '', '', ''),
('Neuzeit-Office', 0, 'font', '', '', ''),
('AauxNext', 0, 'font', '', '', ''),
('Bebas Neue', 0, 'font', '', '', ''),
('RingsideCondensed', 0, 'font', '', '', ''),
('BerninaSans', 0, 'font', '', '', ''),
('BerninoSans', 0, 'font', '', '', ''),
('NightMachine', 0, 'font', '', '', ''),
('SGMT-PostGrotesk', 0, 'font', '', '', ''),
('LaneCane_Regular', 0, 'font', '', '', ''),
('LaneNarrow_Regular', 0, 'font', '', '', ''),
('LanePosh_Regular', 0, 'font', '', '', ''),
('LaneUpper_Regular', 0, 'font', '', '', ''),
('AvantGuard', 0, 'font', '', '', ''),
('CenturyGothic', 0, 'font', '', '', ''),
('BerlingskeSerifText', 0, 'font', '', '', ''),
('DrukCond-Super', 0, 'font', '', '', ''),
('DrukXCond-Super', 0, 'font', '', '', ''),
('Druk-Web', 0, 'font', '', '', ''),
('DrukWide-Web', 0, 'font', '', '', ''),
('AtlasTypewriter', 0, 'font', '', '', ''),
('TiemposHeadline', 0, 'font', '', '', ''),
('TiemposText', 0, 'font', '', '', ''),
('Helvetica-Neue-Extended', 0, 'font', '', '', ''),
('ChronicleHairline', 0, 'font', '', '', ''),
('ChronicleDeck', 0, 'font', '', '', ''),
('ChronicleDisp', 0, 'font', '', '', ''),
('NoeText', 0, 'font', '', '', ''),
('LyonText', 0, 'font', '', '', ''),
('Dinamit', 0, 'font', '', '', ''),
('DIN-Condensed', 0, 'font', '', '', ''),
('Kompakt', 0, 'font', '', '', ''),
('Palatino', 0, 'font', '', '', ''),
('MinionPro', 0, 'font', '', '', ''),
('HaasGroteskDSPro', 0, 'font', '', '', ''),
('ACaslonPro', 0, 'font', '', '', ''),
('Pangram', 0, 'font', '', '', ''),
('SerifGothic', 0, 'font', '', '', ''),
('ZapfDingbats', 0, 'font', '', '', ''),
('Cinetype-Mono', 0, 'font', '', '', ''),
('Helvetica-Neue-Outline', 0, 'font', '', '', ''),
('Helvetica-Neue-Condensed', 0, 'font', '', '', ''),
('Helvetica-Neue', 0, 'font', '', '', ''),
('AvenirPro', 0, 'font', '', '', ''),
('Frutiger', 0, 'font', '', '', ''),
('AkkuratPro', 0, 'font', '', '', ''),
('Apercu', 0, 'font', '', '', ''),
('ApercuMono', 0, 'font', '', '', ''),
('National', 0, 'font', '', '', ''),
('TiemposFine', 0, 'font', '', '', ''),
('Rakuten', 0, 'font', '', '', ''),
('BentonSans', 0, 'font', '', '', ''),
('StagSans', 0, 'font', '', '', ''),
('Suisse', 0, 'font', '', '', ''),
('Georgia', 0, 'font', '', '', ''),
('GeorgiaItalic', 0, 'font', '', '', ''),
('Ageo', 0, 'font', '', '', ''),
('KnockoutWelterweight', 0, 'font', '', '', ''),
('KnockoutMiddleweight', 0, 'font', '', '', ''),
('KnockoutCruiserweight', 0, 'font', '', '', ''),
('Glypha', 0, 'font', '', '', ''),
('SofiaPro', 0, 'font', '', '', ''),
('NeutraText', 0, 'font', '', '', ''),
('NeutraDisplay', 0, 'font', '', '', ''),
('TektonPro-Cond', 0, 'font', '', '', ''),
('queueit', 0, 'font', '', '', ''),
('NimbusSans-Extended', 0, 'font', '', '', ''),
('NimbusSans-Condensed', 0, 'font', '', '', ''),
('NimbusSans-Initials', 0, 'font', '', '', ''),
('NimbusSans-Outline', 0, 'font', '', '', ''),
('NimbusSans-Regular', 0, 'font', '', '', ''),
('NimbusSans-Outline-Extended', 0, 'font', '', '', ''),
('NimbusSans-Light', 0, 'font', '', '', ''),
('NeoSansPro', 0, 'font', '', '', ''),
('NeoSans', 0, 'font', '', '', ''),
('GroteskA', 0, 'font', '', '', ''),
('GroteskB', 0, 'font', '', '', ''),
('BreveDisplay', 0, 'font', '', '', ''),
('GillSans', 0, 'font', '', '', ''),
('NeoSansStd', 0, 'font', '', '', ''),
('AcuminPro', 0, 'font', '', '', ''),
('BMWTypeV2', 0, 'font', '', '', ''),
('BergenMono', 0, 'font', '', '', ''),
('AwesomeWebFont', 0, 'font', '', '', ''),
('MetaPro', 0, 'font', '', '', ''),
('GreyCliff', 0, 'font', '', '', ''),
('TradeGothic', 0, 'font', '', '', ''),
('Ford-Antenna', 0, 'font', '', '', ''),
('Ford-Antenna-Comp', 0, 'font', '', '', ''),
('Ford-Antenna-ExtraCond', 0, 'font', '', '', ''),
('Ford-Antenna-Cond', 0, 'font', '', '', ''),
('StargazeStencil', 0, 'font', '', '', ''),
('Stargaze', 0, 'font', '', '', ''),
('Signatra', 0, 'font', '', '', ''),
('VisbyCF', 0, 'font', '', '', ''),
('GT-America-Mono', 0, 'font', '', '', ''),
('GT-America-Regular', 0, 'font', '', '', ''),
('RobotoBlack', 0, 'font', '', '', ''),
('Folio-Std', 0, 'font', '', '', ''),
('ZonaPro', 0, 'font', '', '', ''),
('OldPress', 0, 'font', '', '', ''),
('NorthPort', 0, 'font', '', '', ''),
('KhakiStd', 0, 'font', '', '', ''),
('Eurostile', 0, 'font', '', '', ''),
('FunctionPro-Stencil', 0, 'font', '', '', ''),
('FunctionPro-Condensed', 0, 'font', '', '', ''),
('FunctionPro', 0, 'font', '', '', ''),
('FunctionCaps', 0, 'font', '', '', ''),
('Hellix', 0, 'font', '', '', ''),
('Canela', 0, 'font', '', '', ''),
('Titling-Gothic-Narrow', 0, 'font', '', '', ''),
('Titling-Gothic-Normal', 0, 'font', '', '', ''),
('Titling-Gothic-Skyline', 0, 'font', '', '', ''),
('Titling-Gothic-Wide', 0, 'font', '', '', ''),
('FarnhamText', 0, 'font', '', '', ''),
('Gingrich-Deck', 0, 'font', '', '', ''),
('Optima', 0, 'font', '', '', ''),
('Gobold', 0, 'font', '', '', ''),
('Metric', 0, 'font', '', '', ''),
('Whitney', 0, 'font', '', '', ''),
('Korolev', 0, 'font', '', '', ''),
('VWHead', 0, 'font', '', '', ''),
('VWText', 0, 'font', '', '', ''),
('Mont', 0, 'font', '', '', ''),
('AvantGardeGothic', 0, 'font', '', '', ''),
('AmazonEmberCd', 0, 'font', '', '', ''),
('AmazonEmber', 0, 'font', '', '', ''),
('Franklin-Gothic-Comp-Book', 0, 'font', '', '', '');