INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('admin',100,'advanced',NULL,NULL,NULL)
,('progressTask',100,'advanced',NULL,NULL,NULL)
,('deleteContact',100,'advanced',NULL,NULL,NULL)
,('advancedSearch',100,'advanced',NULL,NULL,NULL)
,('personalization',100,'advanced',NULL,NULL,NULL)
,('salesforce',0,'package','If chosen as the 1 included integration by the client...','[Integrations] Salesforce integration',NULL)
,('mailchimp',100,'advanced',NULL,NULL,NULL)
,('Gotham',0,'font',NULL,NULL,NULL)
,('AvenirNext',0,'font',NULL,NULL,NULL)
,('removeBranding',0,'advanced',NULL,'[Branding] ONLY Remove Bizzabo Branding',NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('mergeContact',100,'advanced',NULL,NULL,NULL)
,('rtl',0,'advanced','For websites in Hebrew, Arabic','[Website Editor] Right to Left',NULL)
,('Taz',0,'font',NULL,NULL,NULL)
,('hideAmericanExpressIcon',0,'advanced',NULL,'[Registration] Hide Amex icon',NULL)
,('swapWithMoney',100,'advanced',NULL,NULL,NULL)
,('newCommunity',100,'advanced',NULL,NULL,NULL)
,('Cinetype',0,'font',NULL,NULL,NULL)
,('websiteCss',0,'advanced',NULL,'[Website Editor - Branding] ONLY Custom CSS',NULL)
,('sessionRegistration',0,'package',NULL,'[Agenda] Session Registraion','pro')
,('apiKeys',0,'package',NULL,'[Integrations] Open Public API','elite')
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('rsvpForm',0,'development',NULL,'[Registration] RSVP via Form (Test)',NULL)
,('boomset',100,'advanced',NULL,NULL,NULL)
,('kievietFont',0,'font',NULL,NULL,NULL)
,('taxOnCheckout',100,'advanced',NULL,NULL,NULL)
,('Calibri',0,'font',NULL,NULL,NULL)
,('Graphik',0,'font',NULL,NULL,NULL)
,('TitlingGothicCompressed',0,'font',NULL,NULL,NULL)
,('newPollsUI',100,'advanced',NULL,NULL,NULL)
,('removeTicketWidgetLinkedin',0,'advanced',NULL,'[Registration] Remove Linkedin Integration',NULL)
,('seo',0,'advanced',NULL,'[Website Editor - Branding] ONLY Seo',NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('brandingPackage',0,'package',NULL,'[Branding] Branding Package','pro')
,('AdelleSans',0,'font',NULL,NULL,NULL)
,('showRegistrationDashboard',100,'advanced',NULL,NULL,NULL)
,('showRevenueDashboard',0,'development',NULL,'[Dashboard] Show Revenue Dashabord',NULL)
,('showEmailMarketingDashboard',0,'development',NULL,'[Email] Analytics Email',NULL)
,('googleTagManager',100,'advanced',NULL,NULL,NULL)
,('Proxima',0,'font',NULL,NULL,NULL)
,('LeagueGothic',0,'font',NULL,NULL,NULL)
,('SEGFoco',0,'font',NULL,NULL,NULL)
,('analyticsNew',100,'advanced',NULL,NULL,NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('ticketsTransfer',100,'advanced',NULL,NULL,NULL)
,('LinetoCircular',0,'font',NULL,NULL,NULL)
,('GT-Pressura-Mono',0,'font',NULL,NULL,NULL)
,('hotLeads',100,'advanced',NULL,NULL,NULL)
,('Tungsten',0,'font',NULL,NULL,NULL)
,('Neue-Hass-Grotesk',0,'font',NULL,NULL,NULL)
,('Gilroy',0,'font',NULL,NULL,NULL)
,('editPaymentCredentials',100,'advanced',NULL,NULL,NULL)
,('GoogleSans',0,'font',NULL,NULL,NULL)
,('PostazBold-Regular',0,'font',NULL,NULL,NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('BarleyScript',0,'font',NULL,NULL,NULL)
,('Franklin-Gothic-Book',0,'font',NULL,NULL,NULL)
,('Franklin-Gothic-Demi',0,'font',NULL,NULL,NULL)
,('Helvetica',0,'font',NULL,NULL,NULL)
,('Locator',0,'font',NULL,NULL,NULL)
,('customJs',0,'advanced',NULL,'[Website Editor] Custom JavaScript',NULL)
,('OctoberMoon',0,'font',NULL,NULL,NULL)
,('agendaSBSView',100,'advanced',NULL,NULL,NULL)
,('agendaAnalytics',100,'advanced',NULL,NULL,NULL)
,('CircularStd',0,'font',NULL,NULL,NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('whiteLabelDomain',0,'advanced',NULL,'[Branding] ONLY White Label Domain',NULL)
,('agendaAnalyticsSpeakers',100,'advanced',NULL,NULL,NULL)
,('ProximaNova-CS',0,'font',NULL,NULL,NULL)
,('MyriadPro',0,'font',NULL,NULL,NULL)
,('MyriadPro-Semi-Condensed',0,'font',NULL,NULL,NULL)
,('MyriadPro-Semi-Extended',0,'font',NULL,NULL,NULL)
,('agendaBanner',100,'advanced',NULL,NULL,NULL)
,('useTokensCache',100,'advanced',NULL,NULL,NULL)
,('customCode',0,'advanced',NULL,'[Website Editor - Branding] ONLY Custom Code',NULL)
,('whiteLabelApp',0,'package',NULL,'[App] White Label Mobile App',NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('LuxuryText',0,'font',NULL,NULL,NULL)
,('crossEventAnalyticsV2',100,'advanced',NULL,NULL,NULL)
,('ArtegraSans',0,'font',NULL,NULL,NULL)
,('xtag',0,'package',NULL,'[Integrations] Xtag Onsite Solutions',NULL)
,('ZingRustBase',0,'font',NULL,NULL,NULL)
,('ZingRustHalftone',0,'font',NULL,NULL,NULL)
,('ZingRustLine',0,'font',NULL,NULL,NULL)
,('pollById',0,'advanced',NULL,'[Polls] Poll by ID',NULL)
,('Franklin-Gothic-CnSC-Book',0,'font',NULL,NULL,NULL)
,('Franklin-Gothic-CnSC-Medium',0,'font',NULL,NULL,NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('Franklin-Gothic-Comp-Book',0,'font',NULL,NULL,NULL)
,('FranklinGothic-Ext-Comp-Book',0,'font',NULL,NULL,NULL)
,('FranklinGothic-Cond-Book',0,'font',NULL,NULL,NULL)
,('FranklinGothic-Cond-Demi',0,'font',NULL,NULL,NULL)
,('Roska',0,'font',NULL,NULL,NULL)
,('PromoCodeImportXls',0,'advanced',NULL,'[Registration] Promo Code Import Xls',NULL)
,('ticketSelectionPopover',0,'advanced',NULL,'[Registration] Ticket Selection Popover',NULL)
,('BrandonGrotesque',0,'font',NULL,NULL,NULL)
,('AlternateGothic',0,'font',NULL,NULL,NULL)
,('valuesMappingEnabled',0,'advanced',NULL,'[Registration] Values Mapping Enabled',NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('DINPro',0,'font',NULL,NULL,NULL)
,('DirtyHeadline',0,'font',NULL,NULL,NULL)
,('agendaSessReg',100,'advanced',NULL,NULL,NULL)
,('Novecentowide',0,'font',NULL,NULL,NULL)
,('Plantagenet-Cherokee',0,'font',NULL,NULL,NULL)
,('Segoe-Ui',0,'font',NULL,NULL,NULL)
,('Futura-Condensed',0,'font',NULL,NULL,NULL)
,('Futura',0,'font',NULL,NULL,NULL)
,('Segoe-Ui-Light',0,'font',NULL,NULL,NULL)
,('Segoe-Ui-SemiBold',0,'font',NULL,NULL,NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('Segoe-Ui-SemiLight',0,'font',NULL,NULL,NULL)
,('hideBizzaboTerms',0,'advanced',NULL,'[Registration] Hide Bizzabo Terms And Conditions (Upon Legal Team Approval)',NULL)
,('Fabrikat-Mono',0,'font',NULL,NULL,NULL)
,('NexaSlab',0,'font',NULL,NULL,NULL)
,('UniNeue',0,'font',NULL,NULL,NULL)
,('enableAptrinsicTool',100,'advanced',NULL,NULL,NULL)
,('speakersManageOrders',100,'advanced',NULL,NULL,NULL)
,('lockerAgendaAnalytics',100,'advanced',NULL,NULL,NULL)
,('newCustomElement',100,'advanced',NULL,NULL,NULL)
,('eventProperties',100,'advanced',NULL,NULL,NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('Gotham-Condensed',0,'font',NULL,NULL,NULL)
,('Gotham-Rounded',0,'font',NULL,NULL,NULL)
,('BureauGrotesque-Five',0,'font',NULL,NULL,NULL)
,('BureauGrotesque-One',0,'font',NULL,NULL,NULL)
,('BureauGrotesque-Seven',0,'font',NULL,NULL,NULL)
,('BureauGrotesque-Three',0,'font',NULL,NULL,NULL)
,('companyListProfiles',0,'package',NULL,'[Companies] Companies feature','elite')
,('CompassSans',0,'font',NULL,NULL,NULL)
,('CompassSerif',0,'font',NULL,NULL,NULL)
,('ticketsDownloadReport',100,'advanced',NULL,NULL,NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('crossEventsEngagement',100,'advanced',NULL,NULL,NULL)
,('EuclidFlex',0,'font',NULL,NULL,NULL)
,('Neuzeit-Office',0,'font',NULL,NULL,NULL)
,('AauxNext',0,'font',NULL,NULL,NULL)
,('Bebas Neue',0,'font',NULL,NULL,NULL)
,('RingsideCondensed',0,'font',NULL,NULL,NULL)
,('BerninaSans',0,'font',NULL,NULL,NULL)
,('BerninoSans',0,'font',NULL,NULL,NULL)
,('NightMachine',0,'font',NULL,NULL,NULL)
,('emailsCampaigns',100,'advanced',NULL,NULL,NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('eventPropertiesNewUrls',100,'advanced',NULL,NULL,NULL)
,('SGMT-PostGrotesk',0,'font',NULL,NULL,NULL)
,('scheduledEmailCampaigns',100,'advanced',NULL,NULL,NULL)
,('LaneCane_Regular',0,'font',NULL,NULL,NULL)
,('LaneNarrow_Regular',0,'font',NULL,NULL,NULL)
,('LanePosh_Regular',0,'font',NULL,NULL,NULL)
,('LaneUpper_Regular',0,'font',NULL,NULL,NULL)
,('AvantGuard',0,'font',NULL,NULL,NULL)
,('CenturyGothic',0,'font',NULL,NULL,NULL)
,('BerlingskeSerifText',0,'font',NULL,NULL,NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('DrukCond-Super',0,'font',NULL,NULL,NULL)
,('DrukXCond-Super',0,'font',NULL,NULL,NULL)
,('Druk-Web',0,'font',NULL,NULL,NULL)
,('DrukWide-Web',0,'font',NULL,NULL,NULL)
,('AtlasTypewriter',0,'font',NULL,NULL,NULL)
,('TiemposHeadline',0,'font',NULL,NULL,NULL)
,('TiemposText',0,'font',NULL,NULL,NULL)
,('autoOpenSessions',0,'advanced',NULL,'[Agenda] Session Preview Text ''Auto-Expend''',NULL)
,('Geomanist',0,'font',NULL,NULL,NULL)
,('zendeskHelpCenter',100,'advanced',NULL,NULL,NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('disableMoreTabs',0,'advanced',NULL,'[Website Editor] Disable More Tabs',NULL)
,('Helvetica-Neue-Extended',0,'font',NULL,NULL,NULL)
,('newRolesAttributeUrl',100,'advanced',NULL,NULL,NULL)
,('ChronicleHairline',0,'font',NULL,NULL,NULL)
,('ChronicleDeck',0,'font',NULL,NULL,NULL)
,('ChronicleDisp',0,'font',NULL,NULL,NULL)
,('getSeparatedContactsList',100,'advanced',NULL,NULL,NULL)
,('emailBuilderCodeView',0,'advanced','email code view and table capabilities will be added to the Body Element of the email builder.','[Email] Email Builder Code View',NULL)
,('NoeText',0,'font',NULL,NULL,NULL)
,('LyonText',0,'font',NULL,NULL,NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('Dinamit',0,'font',NULL,NULL,NULL)
,('DIN-Condensed',0,'font',NULL,NULL,NULL)
,('Kompakt',0,'font',NULL,NULL,NULL)
,('Palatino',0,'font',NULL,NULL,NULL)
,('MinionPro',0,'font',NULL,NULL,NULL)
,('HaasGroteskDSPro',0,'font',NULL,NULL,NULL)
,('ACaslonPro',0,'font',NULL,NULL,NULL)
,('reactSection',100,'advanced',NULL,NULL,NULL)
,('Pangram',0,'font',NULL,NULL,NULL)
,('SerifGothic',0,'font',NULL,NULL,NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('ZapfDingbats',0,'font',NULL,NULL,NULL)
,('Cinetype-Mono',0,'font',NULL,NULL,NULL)
,('analyticsDashboard',0,'package',NULL,'[Dashboard] Cross Events Analytics','elite')
,('archiveEvent',100,'advanced',NULL,NULL,NULL)
,('insightsDashboard',0,'package',NULL,'[Dashboard] Insights Audience + Cross Events Analytics','elite')
,('Helvetica-Neue-Outline',0,'font',NULL,NULL,NULL)
,('Helvetica-Neue-Condensed',0,'font',NULL,NULL,NULL)
,('Helvetica-Neue',0,'font',NULL,NULL,NULL)
,('testFeature',0,'development',NULL,'[Website Editor] Test Feature',NULL)
,('closeReactSection-header',0,'advanced',NULL,'[Website Editor] Advanced Styles for Header Element',NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('closeReactSection-downloadApp',0,'advanced',NULL,'[Website Editor] Advanced Styles for Download App Element',NULL)
,('stripe3ds',100,'advanced',NULL,NULL,NULL)
,('AvenirPro',0,'font',NULL,NULL,NULL)
,('Frutiger',0,'font',NULL,NULL,NULL)
,('AkkuratPro',0,'font',NULL,NULL,NULL)
,('Apercu',0,'font',NULL,NULL,NULL)
,('ApercuMono',0,'font',NULL,NULL,NULL)
,('National',0,'font',NULL,NULL,NULL)
,('TiemposFine',0,'font',NULL,NULL,NULL)
,('sessionAssociation',0,'development',NULL,'[Agenda] Session Association Private Flow',NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('emailSmartLink',0,'advanced',NULL,'[Email] Save A Seat Smart Link',NULL)
,('Rakuten',0,'font',NULL,NULL,NULL)
,('switchTheme',100,'advanced',NULL,NULL,NULL)
,('switchThemeLivePreview',100,'advanced',NULL,NULL,NULL)
,('disableTicketsDefaultQuantity',0,'advanced',NULL,'[Registration] Disable Tickets Default Quantity',NULL)
,('personalizationCustomAttributes',0,'advanced','all registration attributes will be added to the Registration Confirmation campaigns'' (Automated Emails) personalization tag list.','[Email] Personalization Custom Attributes',NULL)
,('conditionalLogic',0,'advanced',NULL,'[Registration-RSVP] Conditional Logic',NULL)
,('BentonSans',0,'font',NULL,NULL,NULL)
,('StagSans',0,'font',NULL,NULL,NULL)
,('Suisse',0,'font',NULL,NULL,NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('SuisseMono',0,'font',NULL,NULL,NULL)
,('loginSSO',0,'package',NULL,'[Account] Login SSO',NULL)
,('Georgia',0,'font',NULL,NULL,NULL)
,('GeorgiaItalic',0,'font',NULL,NULL,NULL)
,('Ageo',0,'font',NULL,NULL,NULL)
,('KnockoutWelterweight',0,'font',NULL,NULL,NULL)
,('KnockoutMiddleweight',0,'font',NULL,NULL,NULL)
,('KnockoutCruiserweight',0,'font',NULL,NULL,NULL)
,('Glypha',0,'font',NULL,NULL,NULL)
,('SofiaPro',0,'font',NULL,NULL,NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('privateFlow',0,'advanced',NULL,'[Agenda] Private Flow',NULL)
,('MaquettePro',0,'font',NULL,NULL,NULL)
,('dynamicCcEnabled',0,'advanced','the option toggle CC per registrant/contact will be added to all automated/scheduled campaign''s audience tab. ','[Email] Dynamic CC',NULL)
,('ShareAudienceDashboardAction',0,'package',NULL,'[Dashboard] Insights - Share Dashboard ','elite')
,('Flood',0,'font',NULL,NULL,NULL)
,('registrationCap',0,'advanced',NULL,'[Registration] Cap Limit Tickets',NULL)
,('IvarText',0,'font',NULL,NULL,NULL)
,('registrationV2Settings',0,'development',NULL,'[Registration] V2 Settings',NULL)
,('Campton',0,'font',NULL,NULL,NULL)
,('NeutraText',0,'font',NULL,NULL,NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('NeutraDisplay',0,'font',NULL,NULL,NULL)
,('TektonPro-Cond',0,'font',NULL,NULL,NULL)
,('queueit',0,'font',NULL,NULL,NULL)
,('closeReactSection-attendees',0,'development',NULL,'[Website Editor] Close React Section Attendees',NULL)
,('disableUiForTicketsFetch',0,'development',NULL,'[Registration] Disable Ui For Tickets Fetch',NULL)
,('Relative',0,'font',NULL,NULL,NULL)
,('Edo',0,'font',NULL,NULL,NULL)
,('newSectionLayout',100,'advanced',NULL,NULL,NULL)
,('ercFeature',0,'package',NULL,'[ERC] Partners Portal',NULL)
,('srcFeature',0,'package',NULL,'[SRC] Speakers Portal',NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('WLAPreviewImages',0,'package',NULL,'[App] WLA Stores Images Automation',NULL)
,('NimbusSans-Extended',0,'font',NULL,NULL,NULL)
,('NimbusSans-Condensed',0,'font',NULL,NULL,NULL)
,('NimbusSans-Initials',0,'font',NULL,NULL,NULL)
,('NimbusSans-Outline',0,'font',NULL,NULL,NULL)
,('NimbusSans-Regular',0,'font',NULL,NULL,NULL)
,('NimbusSans-Outline-Extended',0,'font',NULL,NULL,NULL)
,('NimbusSans-Light',0,'font',NULL,NULL,NULL)
,('closeReactSection-people',0,'development',NULL,'[Website Editor] Close React Section People',NULL)
,('Neue-Haas-Grotesk-Display',0,'font',NULL,NULL,NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('enableInsightsDashboardDetails',100,'advanced',NULL,NULL,NULL)
,('Inter',0,'font',NULL,NULL,NULL)
,('accountLevelContactSearch',100,'advanced',NULL,NULL,NULL)
,('websiteTemplates',0,'advanced',NULL,'[Website Editor] Templates',NULL)
,('ROEDashboard',0,'development',NULL,'[Dashboard] ROE Dashboard ',NULL)
,('IHSCustomCountryLabel',0,'advanced',NULL,'[Registration] IHS Custom Country Label',NULL)
,('One-GT-Super-Display',0,'font',NULL,NULL,NULL)
,('GintoNormal',0,'font',NULL,NULL,NULL)
,('One-GT-Super-Text',0,'font',NULL,NULL,NULL)
,('Colfax',0,'font',NULL,NULL,NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('scheduledCampaignResend',0,'advanced',NULL,'[Email] Scheduled Campaign Resend',NULL)
,('NeoSansPro',0,'font',NULL,NULL,NULL)
,('NeoSans',0,'font',NULL,NULL,NULL)
,('GroteskA',0,'font',NULL,NULL,NULL)
,('GroteskB',0,'font',NULL,NULL,NULL)
,('BreveDisplay',0,'font',NULL,NULL,NULL)
,('GillSans',0,'font',NULL,NULL,NULL)
,('NeoSansStd',0,'font',NULL,NULL,NULL)
,('AcuminPro',0,'font',NULL,NULL,NULL)
,('SalesforceSans',0,'font',NULL,NULL,NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('BMWTypeV2',0,'font',NULL,NULL,NULL)
,('BergenMono',0,'font',NULL,NULL,NULL)
,('AwesomeWebFont',0,'font',NULL,NULL,NULL)
,('MetaPro',0,'font',NULL,NULL,NULL)
,('resiadaIntegration',0,'advanced',NULL,'[Integrations] Resiada Hotel Platform',NULL)
,('GreyCliff',0,'font',NULL,NULL,NULL)
,('TradeGothic',0,'font',NULL,NULL,NULL)
,('Ford-Antenna',0,'font',NULL,NULL,NULL)
,('Ford-Antenna-Comp',0,'font',NULL,NULL,NULL)
,('Ford-Antenna-ExtraCond',0,'font',NULL,NULL,NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('Ford-Antenna-Cond',0,'font',NULL,NULL,NULL)
,('StargazeStencil',0,'font',NULL,NULL,NULL)
,('Stargaze',0,'font',NULL,NULL,NULL)
,('Signatra',0,'font',NULL,NULL,NULL)
,('cloudinaryInlineContainer',0,'development',NULL,'[Unknown] Cloudinary Inline Container',NULL)
,('VisbyCF',0,'font',NULL,NULL,NULL)
,('segmentPush',100,'advanced',NULL,NULL,NULL)
,('agendaShare',100,'advanced',NULL,NULL,NULL)
,('GT-America-Mono',0,'font',NULL,NULL,NULL)
,('GT-America-Regular',0,'font',NULL,NULL,NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('Platform',0,'font',NULL,NULL,NULL)
,('dateTimePickerField',0,'advanced',NULL,'[Registration] Date Time Picker Field',NULL)
,('RobotoBlack',0,'font',NULL,NULL,NULL)
,('sessionCasting',0,'package',NULL,'[Virtual] Bizzabo Interact (Interact + External solutions + Embedded player solution)','pro')
,('hideEventDates',100,'advanced',NULL,NULL,NULL)
,('srcInvoiceFeature',0,'development',NULL,'[SRC] Download Invoice Feature',NULL)
,('inSidedSSO',100,'advanced',NULL,NULL,NULL)
,('importLinkedinProfileNewReg',0,'advanced','show linkedin import on RSVP. Should be turned on for those that want to use this feature. Will be replaced with a configuration on the dashboard in the future.','[Registration] RSVP Linkedin Integration ',NULL)
,('Folio-Std',0,'font',NULL,NULL,NULL)
,('hideSessionDates',100,'advanced',NULL,NULL,NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('sessionCheckIn',100,'advanced',NULL,'[Agenda] Session Check In Data',NULL)
,('enterpriseBuild',0,'development','To be enabled by WLA Project Manager','[App] White Label App Enterprise Build',NULL)
,('sessionCastingMegaSession',0,'package',NULL,'[Virtual] Bizzabo Stream','pro')
,('unsubscribeToggle',0,'development','You need Bizzabo legal team approval to enable this FT','[Email] Remove Unsubscribe Footer (Upon Legal Team Approval)',NULL)
,('ZonaPro',0,'font',NULL,NULL,NULL)
,('OldPress',0,'font',NULL,NULL,NULL)
,('NorthPort',0,'font',NULL,NULL,NULL)
,('KhakiStd',0,'font',NULL,NULL,NULL)
,('Eurostile',0,'font',NULL,NULL,NULL)
,('FunctionPro-Stencil',0,'font',NULL,NULL,NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('FunctionPro-Condensed',0,'font',NULL,NULL,NULL)
,('FunctionPro',0,'font',NULL,NULL,NULL)
,('FunctionCaps',0,'font',NULL,NULL,NULL)
,('sessionRecording',0,'package','Enables recording of the virtual session','[Virtual] Recording On-Demand','pro')
,('Hellix',0,'font',NULL,NULL,NULL)
,('Canela',0,'font',NULL,NULL,NULL)
,('Titling-Gothic-Narrow',0,'font',NULL,NULL,NULL)
,('Titling-Gothic-Normal',0,'font',NULL,NULL,NULL)
,('Titling-Gothic-Skyline',0,'font',NULL,NULL,NULL)
,('Titling-Gothic-Wide',0,'font',NULL,NULL,NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('FarnhamText',0,'font',NULL,NULL,NULL)
,('Gingrich-Deck',0,'font',NULL,NULL,NULL)
,('Optima',0,'font',NULL,NULL,NULL)
,('Gobold',0,'font',NULL,NULL,NULL)
,('Metric',0,'font',NULL,NULL,NULL)
,('Whitney',0,'font',NULL,NULL,NULL)
,('sessionPrerecordedVideo',0,'development',NULL,'[Virtual] Pre Recorded Video - Simulive',NULL)
,('agendaVirtualAnalytics',0,'package',NULL,'[Virtual] Agenda Virtual Analytics','pro')
,('sessionModerators',100,'advanced',NULL,NULL,NULL)
,('Korolev',0,'font',NULL,NULL,NULL)
;
INSERT INTO toggle_all (feature,percent,`type`,description,label,plan) VALUES 
('VWHead',0,'font',NULL,NULL,NULL)
,('VWText',0,'font',NULL,NULL,NULL)
,('Mont',0,'font',NULL,NULL,NULL)
,('AvantGardeGothic',0,'font',NULL,NULL,NULL)
,('AmazonEmberCd',0,'font',NULL,NULL,NULL)
,('AmazonEmber',0,'font',NULL,NULL,NULL)
,('sessionCaptionsSimulive',0,'development',NULL,'[Virtual] Session Captions Simulive Test for SF ONLY',NULL)
,('sessionLivestream',0,'advanced',NULL,NULL,NULL)
,('hideEmptyDays',0,'advanced',NULL,NULL,NULL)
;