UPDATE toggle_all SET type = "package", label = "[Agenda] Session Registraion", plan = "pro" WHERE feature = "sessionRegistration";
UPDATE toggle_all SET type = "development", label = "[Dashboard] Show Revenue Dashabord" WHERE feature = "showRevenueDashboard";
UPDATE toggle_all SET type = "development", label = "[Email] Analytics Email" WHERE feature = "showEmailMarketingDashboard";
UPDATE toggle_all SET type = "package", label = "[Branding] Branding Package", plan = "pro" WHERE feature = "brandingPackage";
UPDATE toggle_all SET type = "advanced", label = "[Website Editor - Branding] ONLY Custom CSS" WHERE feature = "websiteCss";
UPDATE toggle_all SET type = "advanced", label = "[Website Editor] Custom JavaScript" WHERE feature = "customJs";
UPDATE toggle_all SET type = "advanced", label = "[Registration] Hide Amex icon" WHERE feature = "hideAmericanExpressIcon";
UPDATE toggle_all SET type = "package", label = "[Integrations] Open Public API", plan = "elite" WHERE feature = "apiKeys";
UPDATE toggle_all SET type = "advanced", label = "[Branding] ONLY Remove Bizzabo Branding" WHERE feature = "removeBranding";
UPDATE toggle_all SET type = "advanced", description = "For websites in Hebrew, Arabic", label = "[Website Editor] Right to Left" WHERE feature = "rtl";
UPDATE toggle_all SET type = "package", description = "If chosen as the 1 included integration by the client...", label = "[Integrations] Salesforce integration" WHERE feature = "salesforce";
UPDATE toggle_all SET type = "advanced", label = "[Website Editor - Branding] ONLY Seo" WHERE feature = "seo";
UPDATE toggle_all SET type = "package", label = "[App] White Label Mobile App" WHERE feature = "whiteLabelApp";
UPDATE toggle_all SET type = "package", label = "[App] WLA Stores Settings" WHERE feature = "White Label App - Only Navigation";
UPDATE toggle_all SET type = "development", label = "[Registration] RSVP via Form (Test)" WHERE feature = "rsvpForm";
UPDATE toggle_all SET type = "advanced", label = "[Registration] Remove Linkedin Integration" WHERE feature = "removeTicketWidgetLinkedin";
UPDATE toggle_all SET type = "advanced", label = "[Branding] ONLY White Label Domain" WHERE feature = "whiteLabelDomain";
UPDATE toggle_all SET type = "advanced", label = "[Website Editor - Branding] ONLY Custom Code" WHERE feature = "customCode";
UPDATE toggle_all SET type = "package", label = "[Integrations] Xtag Onsite Solutions" WHERE feature = "xtag";
UPDATE toggle_all SET type = "advanced", label = "[Registration] Promo Code Import Xls" WHERE feature = "PromoCodeImportXls";
UPDATE toggle_all SET type = "advanced", label = "[Registration] Ticket Selection Popover" WHERE feature = "ticketSelectionPopover";
UPDATE toggle_all SET type = "advanced", label = "[Registration] Values Mapping Enabled" WHERE feature = "valuesMappingEnabled";
UPDATE toggle_all SET type = "advanced", label = "[Registration] Hide Bizzabo Terms And Conditions (Upon Legal Team Approval)" WHERE feature = "hideBizzaboTerms";
UPDATE toggle_all SET type = "package", label = "[Companies] Companies feature", plan = "elite" WHERE feature = "companyListProfiles";
UPDATE toggle_all SET type = "advanced", label = "[Agenda] Session Preview Text 'Auto-Expend'" WHERE feature = "autoOpenSessions";
UPDATE toggle_all SET type = "advanced", label = "[Website Editor] Disable More Tabs" WHERE feature = "disableMoreTabs";
UPDATE toggle_all SET type = "advanced", description = "email code view and table capabilities will be added to the Body Element of the email builder.", label = "[Email] Email Builder Code View" WHERE feature = "emailBuilderCodeView";
UPDATE toggle_all SET type = "package", label = "[Dashboard] Cross Events Analytics", plan = "elite" WHERE feature = "analyticsDashboard";
UPDATE toggle_all SET type = "package", label = "[Dashboard] Insights Audience + Cross Events Analytics", plan = "elite" WHERE feature = "insightsDashboard";
UPDATE toggle_all SET type = "development", label = "[Website Editor] Test Feature" WHERE feature = "testFeature";
UPDATE toggle_all SET type = "advanced", label = "[Website Editor] Advanced Styles for Header Element" WHERE feature = "closeReactSection-header";
UPDATE toggle_all SET type = "advanced", label = "[Website Editor] Advanced Styles for Download App Element" WHERE feature = "closeReactSection-downloadApp";
UPDATE toggle_all SET type = "development", label = "[Meetings] Meetings" WHERE feature = "meetingsFeature";
UPDATE toggle_all SET type = "development", label = "[Agenda] Session Association Private Flow" WHERE feature = "sessionAssociation";
UPDATE toggle_all SET type = "advanced", label = "[Email] Save A Seat Smart Link" WHERE feature = "emailSmartLink";
UPDATE toggle_all SET type = "advanced", label = "[Registration] Disable Tickets Default Quantity" WHERE feature = "disableTicketsDefaultQuantity";
UPDATE toggle_all SET type = "advanced", description = "all registration attributes will be added to the Registration Confirmation campaigns' (Automated Emails) personalization tag list.", label = "[Email] Personalization Custom Attributes" WHERE feature = "personalizationCustomAttributes";
UPDATE toggle_all SET type = "advanced", label = "[Registration-RSVP] Conditional Logic" WHERE feature = "conditionalLogic";
UPDATE toggle_all SET type = "package", label = "[Account] Login SSO" WHERE feature = "loginSSO";
UPDATE toggle_all SET type = "advanced", label = "[Agenda] Private Flow" WHERE feature = "privateFlow";
UPDATE toggle_all SET type = "advanced", description = "the option toggle CC per registrant/contact will be added to all automated/scheduled campaign's audience tab. ", label = "[Email] Dynamic CC" WHERE feature = "dynamicCcEnabled";
UPDATE toggle_all SET type = "package", label = "[Dashboard] Insights - Share Dashboard ", plan = "elite" WHERE feature = "ShareAudienceDashboardAction";
UPDATE toggle_all SET type = "advanced", label = "[Registration] Cap Limit Tickets" WHERE feature = "registrationCap";
UPDATE toggle_all SET type = "development", label = "[Registration] V2 Settings" WHERE feature = "registrationV2Settings";
UPDATE toggle_all SET type = "development", label = "[Website Editor] Close React Section Attendees" WHERE feature = "closeReactSection-attendees";
UPDATE toggle_all SET type = "development", label = "[Registration] Disable Ui For Tickets Fetch" WHERE feature = "disableUiForTicketsFetch";
UPDATE toggle_all SET type = "package", label = "[ERC] Partners Portal" WHERE feature = "ercFeature";
UPDATE toggle_all SET type = "package", label = "[SRC] Speakers Portal" WHERE feature = "srcFeature";
UPDATE toggle_all SET type = "package", label = "[App] WLA Stores Images Automation" WHERE feature = "WLAPreviewImages";
UPDATE toggle_all SET type = "development", label = "[Website Editor] Close React Section People" WHERE feature = "closeReactSection-people";
UPDATE toggle_all SET type = "advanced", label = "[Website Editor] Templates" WHERE feature = "websiteTemplates";
UPDATE toggle_all SET type = "development", label = "[Dashboard] ROE Dashboard " WHERE feature = "ROEDashboard";
UPDATE toggle_all SET type = "advanced", label = "[Registration] IHS Custom Country Label" WHERE feature = "IHSCustomCountryLabel";
UPDATE toggle_all SET type = "advanced", label = "[Email] Scheduled Campaign Resend" WHERE feature = "scheduledCampaignResend";
UPDATE toggle_all SET type = "advanced", label = "[Integrations] Resiada Hotel Platform" WHERE feature = "resiadaIntegration";
UPDATE toggle_all SET type = "development", label = "[Unknown] Cloudinary Inline Container" WHERE feature = "cloudinaryInlineContainer";
UPDATE toggle_all SET type = "advanced", label = "[Registration] Date Time Picker Field" WHERE feature = "dateTimePickerField";
UPDATE toggle_all SET type = "package", label = "[Virtual] Bizzabo Interact (Interact + External solutions + Embedded player solution)", plan = "pro" WHERE feature = "sessionCasting";
UPDATE toggle_all SET type = "development", label = "[SRC] Download Invoice Feature" WHERE feature = "srcInvoiceFeature";
UPDATE toggle_all SET type = "advanced", description = "show linkedin import on RSVP. Should be turned on for those that want to use this feature. Will be replaced with a configuration on the dashboard in the future.", label = "[Registration] RSVP Linkedin Integration " WHERE feature = "importLinkedinProfileNewReg";
UPDATE toggle_all SET type = "advanced", label = "[Agenda] Session Check In Data" WHERE feature = "sessionCheckIn";
UPDATE toggle_all SET type = "development", description = "To be enabled by WLA Project Manager", label = "[App] White Label App Enterprise Build" WHERE feature = "enterpriseBuild";
UPDATE toggle_all SET type = "package", label = "[Virtual] Bizzabo Stream", plan = "pro" WHERE feature = "sessionCastingMegaSession";
UPDATE toggle_all SET type = "development", description = "You need Bizzabo legal team approval to enable this FT", label = "[Email] Remove Unsubscribe Footer (Upon Legal Team Approval)" WHERE feature = "unsubscribeToggle";
UPDATE toggle_all SET type = "package", description = "Enables recording of the virtual session", label = "[Virtual] Recording On-Demand", plan = "pro" WHERE feature = "sessionRecording";
UPDATE toggle_all SET type = "package", label = "[Virtual] Agenda Virtual Analytics", plan = "pro" WHERE feature = "agendaVirtualAnalytics";
UPDATE toggle_all SET type = "advanced", label = "[Polls] Poll by ID" WHERE feature = "pollById";
UPDATE toggle_all SET type = "development", label = "[Virtual] Pre Recorded Video - Simulive" WHERE feature = "sessionPrerecordedVideo";
UPDATE toggle_all SET type = "development", label = "[Virtual] Session Captions Simulive Test for SF ONLY" WHERE feature = "sessionCaptionsSimulive";


UPDATE toggle_all SET type = "font" WHERE feature = "Gotham";
UPDATE toggle_all SET type = "font" WHERE feature = "Geomanist";
UPDATE toggle_all SET type = "font" WHERE feature = "Plantagenet-Cherokee";
UPDATE toggle_all SET type = "font" WHERE feature = "Segoe-Ui";
UPDATE toggle_all SET type = "font" WHERE feature = "SuisseMono";
UPDATE toggle_all SET type = "font" WHERE feature = "MaquettePro";
UPDATE toggle_all SET type = "font" WHERE feature = "Flood";
UPDATE toggle_all SET type = "font" WHERE feature = "IvarText";
UPDATE toggle_all SET type = "font" WHERE feature = "Campton";
UPDATE toggle_all SET type = "font" WHERE feature = "Relative";
UPDATE toggle_all SET type = "font" WHERE feature = "Edo";
UPDATE toggle_all SET type = "font" WHERE feature = "Taz";
UPDATE toggle_all SET type = "font" WHERE feature = "AvenirNext";
UPDATE toggle_all SET type = "font" WHERE feature = "Cinetype";
UPDATE toggle_all SET type = "font" WHERE feature = "kievietFont";
UPDATE toggle_all SET type = "font" WHERE feature = "Calibri";
UPDATE toggle_all SET type = "font" WHERE feature = "Graphik";
UPDATE toggle_all SET type = "font" WHERE feature = "TitlingGothicCompressed";
UPDATE toggle_all SET type = "font" WHERE feature = "AdelleSans";
UPDATE toggle_all SET type = "font" WHERE feature = "Proxima";
UPDATE toggle_all SET type = "font" WHERE feature = "LeagueGothic";
UPDATE toggle_all SET type = "font" WHERE feature = "SEGFoco";
UPDATE toggle_all SET type = "font" WHERE feature = "LinetoCircular";
UPDATE toggle_all SET type = "font" WHERE feature = "GT-Pressura-Mono";
UPDATE toggle_all SET type = "font" WHERE feature = "Tungsten";
UPDATE toggle_all SET type = "font" WHERE feature = "Neue-Hass-Grotesk";
UPDATE toggle_all SET type = "font" WHERE feature = "Gilroy";
UPDATE toggle_all SET type = "font" WHERE feature = "GoogleSans";
UPDATE toggle_all SET type = "font" WHERE feature = "PostazBold-Regular";
UPDATE toggle_all SET type = "font" WHERE feature = "BarleyScript";
UPDATE toggle_all SET type = "font" WHERE feature = "Neue-Haas-Grotesk-Display";
UPDATE toggle_all SET type = "font" WHERE feature = "Inter";
UPDATE toggle_all SET type = "font" WHERE feature = "SalesforceSans";
UPDATE toggle_all SET type = "font" WHERE feature = "One-GT-Super-Display";
UPDATE toggle_all SET type = "font" WHERE feature = "GintoNormal";
UPDATE toggle_all SET type = "font" WHERE feature = "One-GT-Super-Text";
UPDATE toggle_all SET type = "font" WHERE feature = "Colfax";
UPDATE toggle_all SET type = "font" WHERE feature = "Franklin-Gothic-Book";
UPDATE toggle_all SET type = "font" WHERE feature = "Franklin-Gothic-Demi";
UPDATE toggle_all SET type = "font" WHERE feature = "Helvetica";
UPDATE toggle_all SET type = "font" WHERE feature = "Locator";
UPDATE toggle_all SET type = "font" WHERE feature = "OctoberMoon";
UPDATE toggle_all SET type = "font" WHERE feature = "CircularStd";
UPDATE toggle_all SET type = "font" WHERE feature = "ProximaNova-CS";
UPDATE toggle_all SET type = "font" WHERE feature = "MyriadPro";
UPDATE toggle_all SET type = "font" WHERE feature = "MyriadPro-Semi-Condensed";
UPDATE toggle_all SET type = "font" WHERE feature = "MyriadPro-Semi-Extended";
UPDATE toggle_all SET type = "font" WHERE feature = "LuxuryText";
UPDATE toggle_all SET type = "font" WHERE feature = "ArtegraSans";
UPDATE toggle_all SET type = "font" WHERE feature = "ZingRustBase";
UPDATE toggle_all SET type = "font" WHERE feature = "ZingRustHalftone";
UPDATE toggle_all SET type = "font" WHERE feature = "ZingRustLine";
UPDATE toggle_all SET type = "font" WHERE feature = "Franklin-Gothic-CnSC-Book";
UPDATE toggle_all SET type = "font" WHERE feature = "Franklin-Gothic-CnSC-Medium";
UPDATE toggle_all SET type = "font" WHERE feature = "Franklin-Gothic-CnSC-Medium";
UPDATE toggle_all SET type = "font" WHERE feature = "FranklinGothic-Ext-Comp-Book";
UPDATE toggle_all SET type = "font" WHERE feature = "FranklinGothic-Cond-Book";
UPDATE toggle_all SET type = "font" WHERE feature = "FranklinGothic-Cond-Demi";
UPDATE toggle_all SET type = "font" WHERE feature = "Roska";
UPDATE toggle_all SET type = "font" WHERE feature = "BrandonGrotesque";
UPDATE toggle_all SET type = "font" WHERE feature = "AlternateGothic";
UPDATE toggle_all SET type = "font" WHERE feature = "DINPro";
UPDATE toggle_all SET type = "font" WHERE feature = "DirtyHeadline";
UPDATE toggle_all SET type = "font" WHERE feature = "Novecentowide";
UPDATE toggle_all SET type = "font" WHERE feature = "Futura-Condensed";
UPDATE toggle_all SET type = "font" WHERE feature = "Futura";
UPDATE toggle_all SET type = "font" WHERE feature = "Segoe-Ui-Light";
UPDATE toggle_all SET type = "font" WHERE feature = "Segoe-Ui-SemiBold";
UPDATE toggle_all SET type = "font" WHERE feature = "Segoe-Ui-SemiLight";
UPDATE toggle_all SET type = "font" WHERE feature = "Fabrikat-Mono";
UPDATE toggle_all SET type = "font" WHERE feature = "NexaSlab";
UPDATE toggle_all SET type = "font" WHERE feature = "UniNeue";
UPDATE toggle_all SET type = "font" WHERE feature = "Gotham-Condensed";
UPDATE toggle_all SET type = "font" WHERE feature = "Gotham-Rounded";
UPDATE toggle_all SET type = "font" WHERE feature = "BureauGrotesque-Five";
UPDATE toggle_all SET type = "font" WHERE feature = "BureauGrotesque-One";
UPDATE toggle_all SET type = "font" WHERE feature = "BureauGrotesque-Seven";
UPDATE toggle_all SET type = "font" WHERE feature = "BureauGrotesque-Three";
UPDATE toggle_all SET type = "font" WHERE feature = "CompassSans";
UPDATE toggle_all SET type = "font" WHERE feature = "CompassSerif";
UPDATE toggle_all SET type = "font" WHERE feature = "EuclidFlex";
UPDATE toggle_all SET type = "font" WHERE feature = "Neuzeit-Office";
UPDATE toggle_all SET type = "font" WHERE feature = "AauxNext";
UPDATE toggle_all SET type = "font" WHERE feature = "Bebas Neue";
UPDATE toggle_all SET type = "font" WHERE feature = "RingsideCondensed";
UPDATE toggle_all SET type = "font" WHERE feature = "BerninaSans";
UPDATE toggle_all SET type = "font" WHERE feature = "BerninoSans";
UPDATE toggle_all SET type = "font" WHERE feature = "NightMachine";
UPDATE toggle_all SET type = "font" WHERE feature = "SGMT-PostGrotesk";
UPDATE toggle_all SET type = "font" WHERE feature = "LaneCane_Regular";
UPDATE toggle_all SET type = "font" WHERE feature = "LaneNarrow_Regular";
UPDATE toggle_all SET type = "font" WHERE feature = "LanePosh_Regular";
UPDATE toggle_all SET type = "font" WHERE feature = "LaneUpper_Regular";
UPDATE toggle_all SET type = "font" WHERE feature = "AvantGuard";
UPDATE toggle_all SET type = "font" WHERE feature = "CenturyGothic";
UPDATE toggle_all SET type = "font" WHERE feature = "BerlingskeSerifText";
UPDATE toggle_all SET type = "font" WHERE feature = "DrukCond-Super";
UPDATE toggle_all SET type = "font" WHERE feature = "DrukXCond-Super";
UPDATE toggle_all SET type = "font" WHERE feature = "Druk-Web";
UPDATE toggle_all SET type = "font" WHERE feature = "DrukWide-Web";
UPDATE toggle_all SET type = "font" WHERE feature = "AtlasTypewriter";
UPDATE toggle_all SET type = "font" WHERE feature = "TiemposHeadline";
UPDATE toggle_all SET type = "font" WHERE feature = "TiemposText";
UPDATE toggle_all SET type = "font" WHERE feature = "Helvetica-Neue-Extended";
UPDATE toggle_all SET type = "font" WHERE feature = "ChronicleHairline";
UPDATE toggle_all SET type = "font" WHERE feature = "ChronicleDeck";
UPDATE toggle_all SET type = "font" WHERE feature = "ChronicleDisp";
UPDATE toggle_all SET type = "font" WHERE feature = "NoeText";
UPDATE toggle_all SET type = "font" WHERE feature = "LyonText";
UPDATE toggle_all SET type = "font" WHERE feature = "Dinamit";
UPDATE toggle_all SET type = "font" WHERE feature = "DIN-Condensed";
UPDATE toggle_all SET type = "font" WHERE feature = "Kompakt";
UPDATE toggle_all SET type = "font" WHERE feature = "Palatino";
UPDATE toggle_all SET type = "font" WHERE feature = "MinionPro";
UPDATE toggle_all SET type = "font" WHERE feature = "HaasGroteskDSPro";
UPDATE toggle_all SET type = "font" WHERE feature = "ACaslonPro";
UPDATE toggle_all SET type = "font" WHERE feature = "Pangram";
UPDATE toggle_all SET type = "font" WHERE feature = "SerifGothic";
UPDATE toggle_all SET type = "font" WHERE feature = "ZapfDingbats";
UPDATE toggle_all SET type = "font" WHERE feature = "Cinetype-Mono";
UPDATE toggle_all SET type = "font" WHERE feature = "Helvetica-Neue-Outline";
UPDATE toggle_all SET type = "font" WHERE feature = "Helvetica-Neue-Condensed";
UPDATE toggle_all SET type = "font" WHERE feature = "Helvetica-Neue";
UPDATE toggle_all SET type = "font" WHERE feature = "AvenirPro";
UPDATE toggle_all SET type = "font" WHERE feature = "Frutiger";
UPDATE toggle_all SET type = "font" WHERE feature = "AkkuratPro";
UPDATE toggle_all SET type = "font" WHERE feature = "Apercu";
UPDATE toggle_all SET type = "font" WHERE feature = "ApercuMono";
UPDATE toggle_all SET type = "font" WHERE feature = "National";
UPDATE toggle_all SET type = "font" WHERE feature = "TiemposFine";
UPDATE toggle_all SET type = "font" WHERE feature = "Rakuten";
UPDATE toggle_all SET type = "font" WHERE feature = "BentonSans";
UPDATE toggle_all SET type = "font" WHERE feature = "StagSans";
UPDATE toggle_all SET type = "font" WHERE feature = "Suisse";
UPDATE toggle_all SET type = "font" WHERE feature = "Georgia";
UPDATE toggle_all SET type = "font" WHERE feature = "GeorgiaItalic";
UPDATE toggle_all SET type = "font" WHERE feature = "Ageo";
UPDATE toggle_all SET type = "font" WHERE feature = "KnockoutWelterweight";
UPDATE toggle_all SET type = "font" WHERE feature = "KnockoutMiddleweight";
UPDATE toggle_all SET type = "font" WHERE feature = "KnockoutCruiserweight";
UPDATE toggle_all SET type = "font" WHERE feature = "Glypha";
UPDATE toggle_all SET type = "font" WHERE feature = "SofiaPro";
UPDATE toggle_all SET type = "font" WHERE feature = "NeutraText";
UPDATE toggle_all SET type = "font" WHERE feature = "NeutraDisplay";
UPDATE toggle_all SET type = "font" WHERE feature = "TektonPro-Cond";
UPDATE toggle_all SET type = "font" WHERE feature = "queueit";
UPDATE toggle_all SET type = "font" WHERE feature = "NimbusSans-Extended";
UPDATE toggle_all SET type = "font" WHERE feature = "NimbusSans-Condensed";
UPDATE toggle_all SET type = "font" WHERE feature = "NimbusSans-Initials";
UPDATE toggle_all SET type = "font" WHERE feature = "NimbusSans-Outline";
UPDATE toggle_all SET type = "font" WHERE feature = "NimbusSans-Regular";
UPDATE toggle_all SET type = "font" WHERE feature = "NimbusSans-Outline-Extended";
UPDATE toggle_all SET type = "font" WHERE feature = "NimbusSans-Light";
UPDATE toggle_all SET type = "font" WHERE feature = "NeoSansPro";
UPDATE toggle_all SET type = "font" WHERE feature = "NeoSans";
UPDATE toggle_all SET type = "font" WHERE feature = "GroteskA";
UPDATE toggle_all SET type = "font" WHERE feature = "GroteskB";
UPDATE toggle_all SET type = "font" WHERE feature = "BreveDisplay";
UPDATE toggle_all SET type = "font" WHERE feature = "GillSans";
UPDATE toggle_all SET type = "font" WHERE feature = "NeoSansStd";
UPDATE toggle_all SET type = "font" WHERE feature = "AcuminPro";
UPDATE toggle_all SET type = "font" WHERE feature = "BMWTypeV2";
UPDATE toggle_all SET type = "font" WHERE feature = "BergenMono";
UPDATE toggle_all SET type = "font" WHERE feature = "AwesomeWebFont";
UPDATE toggle_all SET type = "font" WHERE feature = "MetaPro";
UPDATE toggle_all SET type = "font" WHERE feature = "GreyCliff";
UPDATE toggle_all SET type = "font" WHERE feature = "TradeGothic";
UPDATE toggle_all SET type = "font" WHERE feature = "Ford-Antenna";
UPDATE toggle_all SET type = "font" WHERE feature = "Ford-Antenna-Comp";
UPDATE toggle_all SET type = "font" WHERE feature = "Ford-Antenna-ExtraCond";
UPDATE toggle_all SET type = "font" WHERE feature = "Ford-Antenna-Cond";
UPDATE toggle_all SET type = "font" WHERE feature = "StargazeStencil";
UPDATE toggle_all SET type = "font" WHERE feature = "Stargaze";
UPDATE toggle_all SET type = "font" WHERE feature = "Signatra";
UPDATE toggle_all SET type = "font" WHERE feature = "VisbyCF";
UPDATE toggle_all SET type = "font" WHERE feature = "GT-America-Mono";
UPDATE toggle_all SET type = "font" WHERE feature = "GT-America-Regular";
UPDATE toggle_all SET type = "font" WHERE feature = "RobotoBlack";
UPDATE toggle_all SET type = "font" WHERE feature = "Folio-Std";
UPDATE toggle_all SET type = "font" WHERE feature = "ZonaPro";
UPDATE toggle_all SET type = "font" WHERE feature = "OldPress";
UPDATE toggle_all SET type = "font" WHERE feature = "NorthPort";
UPDATE toggle_all SET type = "font" WHERE feature = "KhakiStd";
UPDATE toggle_all SET type = "font" WHERE feature = "Eurostile";
UPDATE toggle_all SET type = "font" WHERE feature = "FunctionPro-Stencil";
UPDATE toggle_all SET type = "font" WHERE feature = "FunctionPro-Condensed";
UPDATE toggle_all SET type = "font" WHERE feature = "FunctionPro";
UPDATE toggle_all SET type = "font" WHERE feature = "FunctionCaps";
UPDATE toggle_all SET type = "font" WHERE feature = "Hellix";
UPDATE toggle_all SET type = "font" WHERE feature = "Canela";
UPDATE toggle_all SET type = "font" WHERE feature = "Titling-Gothic-Narrow";
UPDATE toggle_all SET type = "font" WHERE feature = "Titling-Gothic-Normal";
UPDATE toggle_all SET type = "font" WHERE feature = "Titling-Gothic-Skyline";
UPDATE toggle_all SET type = "font" WHERE feature = "Titling-Gothic-Wide";
UPDATE toggle_all SET type = "font" WHERE feature = "FarnhamText";
UPDATE toggle_all SET type = "font" WHERE feature = "Gingrich-Deck";
UPDATE toggle_all SET type = "font" WHERE feature = "Optima";
UPDATE toggle_all SET type = "font" WHERE feature = "Gobold";
UPDATE toggle_all SET type = "font" WHERE feature = "Metric";
UPDATE toggle_all SET type = "font" WHERE feature = "Whitney";
UPDATE toggle_all SET type = "font" WHERE feature = "Korolev";
UPDATE toggle_all SET type = "font" WHERE feature = "VWHead";
UPDATE toggle_all SET type = "font" WHERE feature = "VWText";
UPDATE toggle_all SET type = "font" WHERE feature = "Mont";
UPDATE toggle_all SET type = "font" WHERE feature = "AvantGardeGothic";
UPDATE toggle_all SET type = "font" WHERE feature = "AmazonEmberCd";
UPDATE toggle_all SET type = "font" WHERE feature = "AmazonEmber";
UPDATE toggle_all SET type = "font" WHERE feature = "Franklin-Gothic-Comp-Book";
UPDATE toggle_all SET type = "font" WHERE feature = "Platform";

UPDATE toggle_all SET type = "advanced" WHERE feature = "admin";
UPDATE toggle_all SET type = "advanced" WHERE feature = "progressTask";
UPDATE toggle_all SET type = "advanced" WHERE feature = "deleteContact";
UPDATE toggle_all SET type = "advanced" WHERE feature = "advancedSearch";
UPDATE toggle_all SET type = "advanced" WHERE feature = "personalization";
UPDATE toggle_all SET type = "advanced" WHERE feature = "mailchimp";
UPDATE toggle_all SET type = "advanced" WHERE feature = "mergeContact";
UPDATE toggle_all SET type = "advanced" WHERE feature = "swapWithMoney";
UPDATE toggle_all SET type = "advanced" WHERE feature = "newCommunity";
UPDATE toggle_all SET type = "advanced" WHERE feature = "boomset";
UPDATE toggle_all SET type = "advanced" WHERE feature = "taxOnCheckout";
UPDATE toggle_all SET type = "advanced" WHERE feature = "newPollsUI";
UPDATE toggle_all SET type = "advanced" WHERE feature = "showRegistrationDashboard";
UPDATE toggle_all SET type = "advanced" WHERE feature = "googleTagManager";
UPDATE toggle_all SET type = "advanced" WHERE feature = "analyticsNew";
UPDATE toggle_all SET type = "advanced" WHERE feature = "ticketsTransfer";
UPDATE toggle_all SET type = "advanced" WHERE feature = "hotLeads";
UPDATE toggle_all SET type = "advanced" WHERE feature = "editPaymentCredentials";
UPDATE toggle_all SET type = "advanced" WHERE feature = "agendaSBSView";
UPDATE toggle_all SET type = "advanced" WHERE feature = "agendaAnalytics";
UPDATE toggle_all SET type = "advanced" WHERE feature = "agendaAnalyticsSpeakers";
UPDATE toggle_all SET type = "advanced" WHERE feature = "agendaBanner";
UPDATE toggle_all SET type = "advanced" WHERE feature = "useTokensCache";
UPDATE toggle_all SET type = "advanced" WHERE feature = "crossEventAnalyticsV2";
UPDATE toggle_all SET type = "advanced" WHERE feature = "agendaSessReg";
UPDATE toggle_all SET type = "advanced" WHERE feature = "enableAptrinsicTool";
UPDATE toggle_all SET type = "advanced" WHERE feature = "speakersManageOrders";
UPDATE toggle_all SET type = "advanced" WHERE feature = "lockerAgendaAnalytics";
UPDATE toggle_all SET type = "advanced" WHERE feature = "newCustomElement";
UPDATE toggle_all SET type = "advanced" WHERE feature = "eventProperties";
UPDATE toggle_all SET type = "advanced" WHERE feature = "ticketsDownloadReport";
UPDATE toggle_all SET type = "advanced" WHERE feature = "crossEventsEngagement";
UPDATE toggle_all SET type = "advanced" WHERE feature = "emailsCampaigns";
UPDATE toggle_all SET type = "advanced" WHERE feature = "eventPropertiesNewUrls";
UPDATE toggle_all SET type = "advanced" WHERE feature = "scheduledEmailCampaigns";
UPDATE toggle_all SET type = "advanced" WHERE feature = "zendeskHelpCenter";
UPDATE toggle_all SET type = "advanced" WHERE feature = "newRolesAttributeUrl";
UPDATE toggle_all SET type = "advanced" WHERE feature = "getSeparatedContactsList";
UPDATE toggle_all SET type = "advanced" WHERE feature = "reactSection";
UPDATE toggle_all SET type = "advanced" WHERE feature = "archiveEvent";
UPDATE toggle_all SET type = "advanced" WHERE feature = "stripe3ds";
UPDATE toggle_all SET type = "advanced" WHERE feature = "switchTheme";
UPDATE toggle_all SET type = "advanced" WHERE feature = "switchThemeLivePreview";
UPDATE toggle_all SET type = "advanced" WHERE feature = "newSectionLayout";
UPDATE toggle_all SET type = "advanced" WHERE feature = "enableInsightsDashboardDetails";
UPDATE toggle_all SET type = "advanced" WHERE feature = "accountLevelContactSearch";
UPDATE toggle_all SET type = "advanced" WHERE feature = "segmentPush";
UPDATE toggle_all SET type = "advanced" WHERE feature = "agendaShare";
UPDATE toggle_all SET type = "advanced" WHERE feature = "hideEventDates";
UPDATE toggle_all SET type = "advanced" WHERE feature = "inSidedSSO";
UPDATE toggle_all SET type = "advanced" WHERE feature = "hideSessionDates";
UPDATE toggle_all SET type = "advanced" WHERE feature = "sessionModerators";

UPDATE toggle_all SET type = "package", label = "[Virtual] All Session Casting Solutions + Recording On-Demand" WHERE feature = "SessionCastingSolutions";
UPDATE toggle_all SET type = "package", label = "[Virtual] Session Casting External Only" WHERE feature = "SessionCastingExternal";
UPDATE toggle_all SET type = "advanced", label = "[Payments] Bizzabo Gateway" WHERE feature = "BizzaboGateway";
UPDATE toggle_all SET type = "advanced", label = "[Payments] Paypal Gateway" WHERE feature = "PaypalGateway";